
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import com.didisoft.pgp.PGPLib;
import com.sun.net.ssl.internal.ssl.Provider;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintStream;
import java.security.Security;
import javax.net.ssl.SSLSocket;
import javax.net.ssl.SSLSocketFactory;
/**
 *
 * @author USER
 */
public class CLIENTINTERFACEE extends javax.swing.JFrame {
  //static Client c=new Client();
           public static String Reciver;
           public static String balance;
           public static String Agents;
           static SSLSocket clientSocket;
    /** Creates new form CLIENTINTERFACEE */
    public CLIENTINTERFACEE() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TransferResult = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 510));
        getContentPane().setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(70, 180, 77, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(60, 210, 77, 20);

        jLabel1.setText("Agent2");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 180, 70, 14);

        jLabel2.setText("balance");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 210, 80, 14);

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 0, 0);

        jButton2.setText("Transfer Money");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 270, 160, 23);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 0, 0);

        TransferResult.setColumns(20);
        TransferResult.setRows(5);
        jScrollPane4.setViewportView(TransferResult);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(10, 320, 388, 106);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RSA", "PGP" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(10, 270, 110, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank-03.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 870, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     //   c.selection=2; // TODO add your handling code here
         
       try{     
           InputStreamReader streamreader = new InputStreamReader(clientSocket.getInputStream());
           BufferedReader  reader = new BufferedReader(streamreader);
           PrintWriter  writer= new PrintWriter(clientSocket.getOutputStream()); 
           balance=jTextField2.getText();
           Reciver=jTextField1.getText();
           String args [] = new String[2];
           
   if (jComboBox1.getSelectedItem().toString().equals("RSA"))
   { 
       
    RSA rsa = new RSA(1024);
    String Reciverenc=rsa.encrypt(Reciver);
    String balanceenc=rsa.encrypt(balance);

   }
   else 
   {
        PGPLib pgp = new PGPLib();
       
//		             String pgpR =   pgp.encryptString(Reciver, "c:\\public.key");
//             String pgpB =   pgp.encryptString(balance, "c:\\public.key");
                      String privateKeyFile = "c:\\private.key";
                      String privateKeyPass = "changeit";
                      String encRec = pgp.encryptString(Reciver, "c:\\public.key");
                      String encBal =   pgp.encryptString(balance, "c:\\public.key");
                      
                       writer.println("PGP");
                       writer.println(encRec);
                       writer.println(encBal);
                       writer.flush();
                       TransferResult.append("\nEncrypted Reciver name : "+encRec+"\nEncrypted Balance : "+encBal);

//     PrintStream out = new PrintStream(new FileOutputStream("filename.txt")) ;
//     out.println(Reciver);
//     out.println(balance);
        boolean asciiArmor = true;
     
        boolean withIntegrityCheck = false;
        
        
        
//                pgp.encryptFile("filename.txt", null, WIDTH, Reciver);
//        pgp.encryptFile("filename.txt", 
//        				"c:\\public.key", 
//        				"encrypted.pgp", 
//        				asciiArmor, 
//        				withIntegrityCheck);
//        TransferResult.setText("file data : filename.txt\npublic key :c:\\public.key\nencrypted data : encrypted.pgp");
//        TransferResult.append("\n\nReciver is : "+Reciver+"\nBalance is : "+balance);
//        
   }
}catch(Exception e) { }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed



    /**
    * @param args the command line arguments
    */

    public static void main(String args[]) {
//		System.setProperty("javax.net.ssl.trustStore","E:\\NS Final\\src\\server.ks");
		System.setProperty("javax.net.ssl.trustStore","server.ks");


//		{
        
//			// Registering the JSSE provider
			Security.addProvider(new Provider());
//		}
try {
     			SSLSocketFactory sslsocketfactory = (SSLSocketFactory)SSLSocketFactory.getDefault();

     clientSocket = (SSLSocket)sslsocketfactory.createSocket("127.0.0.1",5787); 
} catch (Exception e){}

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CLIENTINTERFACEE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TransferResult;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
